Repository LastExTrascendence/frontend, pull requests merged in 2023-12, with the labels that each got.

#4 fix: 다크모드 관련 오류 #3
  frontend/src/app/page.tsx
  frontend/src/ui/css/globals.css
  frontend/src/ui/mainpage/let-logo.tsx
  frontend/src/ui/mainpage/links.tsx
  frontend/src/ui/mainpage/main-login-button.tsx
  frontend/src/ui/mainpage/mainpage.tsx
  frontend/src/ui/overview/sidenav.tsx
Labels: UI/UX

#10 build: project build setting 20231215/#9
  frontend/.eslintrc.json
  frontend/.prettierrc
  frontend/next.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/yarn.lock
Labels: infra

#6 feat: side navigation bar/#5
  frontend/.eslintrc.json
  frontend/.prettierrc
  frontend/next.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/(overview)/(channel)/channel/channel-join/[id]/page.tsx
  frontend/src/app/(overview)/(channel)/channel/page.tsx
  frontend/src/app/(overview)/layout.tsx
  frontend/src/app/(overview)/mainpage/page.tsx
  frontend/src/lib/definitions.ts
  frontend/src/ui/css/globals.css
  frontend/src/ui/mainpage/links.tsx
  frontend/src/ui/overview/nav-links.tsx
  frontend/src/ui/overview/sidenav.tsx
  frontend/src/ui/overview/sidenavbar/followlist-mock.tsx
  frontend/src/ui/overview/sidenavbar/nav-links-logo.tsx
  frontend/src/ui/overview/sidenavbar/nav-links-wrapper.tsx
  frontend/src/ui/overview/sidenavbar/nav-links.tsx
  frontend/src/ui/overview/sidenavbar/sidenav-follow-list-following.tsx
  frontend/src/ui/overview/sidenavbar/sidenav-follow-list-logo.tsx
  frontend/src/ui/overview/sidenavbar/sidenav-follow-list-me.tsx
  frontend/src/ui/overview/sidenavbar/sidenav-follow-list-online-count.tsx
  frontend/src/ui/overview/sidenavbar/sidenav-follow-list.tsx
  frontend/src/utils/myState.ts
  frontend/yarn.lock
Labels: enhancement, UI/UX

#14 feat: top navigation bar/#13
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/getSearchedUser.tsx
  frontend/src/app/(overview)/layout.tsx
  frontend/src/components/search.tsx
  frontend/src/lib/definitions.ts
  frontend/src/ui/css/globals.css
  frontend/src/ui/overview/topnavbar/topnav-mock.tsx
  frontend/src/ui/overview/topnavbar/topnav.tsx
  frontend/src/utils/fetch.ts
  frontend/yarn.lock
Labels: enhancement

#19 feat: basic login process #1
  frontend/next.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/public/LET_logo.svg
  frontend/public/default_profile.svg
  frontend/src/api/axios/axios.custom.ts
  frontend/src/api/axios/axios.instance.ts
  frontend/src/api/cookie/cookies.ts
  frontend/src/app/(overview)/login/page.tsx
  frontend/src/app/login/page.tsx
  frontend/src/app/register/page.tsx
  frontend/src/types/constants/status-code.ts
  frontend/src/types/dto/user.dto.ts
  frontend/src/ui/card.tsx
  frontend/src/ui/css/globals.css
  frontend/src/ui/pill-button.tsx
  frontend/src/ui/profile-image.tsx
  frontend/yarn.lock
Labels: enhancement

#23 refactor: layout and navigation styles
  frontend/src/app/(overview)/layout.tsx
  frontend/src/ui/overview/sidenavbar/nav-links-logo.tsx
  frontend/src/ui/overview/sidenavbar/nav-links-wrapper.tsx
  frontend/src/ui/overview/sidenavbar/nav-links.tsx
  frontend/src/ui/overview/sidenavbar/sidenav-follow-list-following.tsx
  frontend/src/ui/overview/sidenavbar/sidenav-follow-list-logo.tsx
  frontend/src/ui/overview/sidenavbar/sidenav-follow-list-me.tsx
  frontend/src/ui/overview/sidenavbar/sidenav-follow-list-online-count.tsx
  frontend/src/ui/overview/sidenavbar/sidenav-follow-list.tsx
  frontend/tailwind.config.ts
Labels: enhancement

#30 feat(profile): profile페이지 #29
  frontend/src/app/(overview)/profile/page.tsx
  frontend/src/app/login/page.tsx
  frontend/src/ui/user-status/user-card-setting.tsx
  frontend/src/ui/user-status/user-card.tsx
  frontend/src/utils/myState.ts
  frontend/yarn.lock
Labels: enhancement

#27 fix: 메인페이지 수정 및 기타 기능 추가 #25
  frontend/next.config.js
  frontend/public/LET_logo_white.svg
  frontend/public/info.svg
  frontend/public/logout.svg
  frontend/src/app/(overview)/layout.tsx
  frontend/src/app/layout.tsx
  frontend/src/app/login/page.tsx
  frontend/src/app/page.tsx
  frontend/src/lib/definitions.ts
  frontend/src/lib/registry.tsx
  frontend/src/types/interface/icon.interface.ts
  frontend/src/ui/card.tsx
  frontend/src/ui/icon/icon-container.tsx
  frontend/src/ui/icon/info-icon.tsx
  frontend/src/ui/icon/logout-icon.tsx
  frontend/src/ui/mainpage/links.tsx
  frontend/src/ui/mainpage/main-buttons.tsx
  frontend/src/ui/mainpage/mainpage.tsx
  frontend/src/ui/overview/sidenavbar/nav-links-wrapper.tsx
  frontend/src/ui/pill-button.tsx
Labels: enhancement, UI/UX

#31 fix: TopNavBar, SideNavBar 수정 및 Profile 페이지 추가 #28 #29
  frontend/public/LET_logo_light_purple.svg
  frontend/public/chat.svg
  frontend/public/default_profile.svg
  frontend/public/home.svg
  frontend/public/tabletennis.svg
  frontend/src/app/(overview)/layout.tsx
  frontend/src/app/(overview)/profile/page.tsx
  frontend/src/app/page.tsx
  frontend/src/app/register/page.tsx
  frontend/src/components/SearchUser.tsx
  frontend/src/types/interface/button.interface.ts
  frontend/src/types/interface/icon.interface.ts
  frontend/src/ui/css/globals.css
  frontend/src/ui/icon/icon-container.tsx
  frontend/src/ui/input-container.tsx
  frontend/src/ui/let-logo.tsx
  frontend/src/ui/login-form.tsx
  frontend/src/ui/mainpage/let-logo.tsx
  frontend/src/ui/mainpage/main-buttons.tsx
  frontend/src/ui/mainpage/main-login-button.tsx
  frontend/src/ui/multi-toggle-switch.tsx
  frontend/src/ui/overview/sidenavbar/friend/friend-section-card.tsx
  frontend/src/ui/overview/sidenavbar/friend/friend-section-friend-list.tsx
  frontend/src/ui/overview/sidenavbar/friend/friend-section-mystatus.tsx
  frontend/src/ui/overview/sidenavbar/friend/friend-section-online-count.tsx
  frontend/src/ui/overview/sidenavbar/friend/friend-section.tsx
  frontend/src/ui/overview/sidenavbar/nav-links-logo.tsx
  frontend/src/ui/overview/sidenavbar/nav-links-wrapper.tsx
  frontend/src/ui/overview/sidenavbar/nav-links.tsx
  frontend/src/ui/overview/sidenavbar/sidenav-button-list.tsx
  frontend/src/ui/overview/sidenavbar/sidenav-follow-list-following.tsx
  frontend/src/ui/overview/sidenavbar/sidenav-follow-list-logo.tsx
  frontend/src/ui/overview/sidenavbar/sidenav-follow-list-me.tsx
  frontend/src/ui/overview/sidenavbar/sidenav-follow-list-online-count.tsx
  frontend/src/ui/overview/sidenavbar/sidenav-follow-list.tsx
  frontend/src/ui/overview/sidenavbar/sidenav.tsx
  frontend/src/ui/overview/topnavbar/topnav-logo.tsx
  frontend/src/ui/overview/topnavbar/topnav-textlogo.tsx
  frontend/src/ui/overview/topnavbar/topnav.tsx
  frontend/src/ui/pill-button.tsx
  frontend/src/ui/profile-image.tsx
  frontend/src/ui/user-info-card.tsx
  frontend/src/ui/user-status/user-card-setting.tsx
  frontend/src/ui/user-status/user-card.tsx
  frontend/src/utils/myState.ts
Labels: bug, enhancement
