Repository LastExTrascendence/frontend, pull requests merged in 2024-01, with the labels that each got.

#37 fix: window.location.href 를 SPA 규칙에 맞게 수정 #35
  frontend/src/api/axios/axios.custom.ts
  frontend/src/app/register/page.tsx
  frontend/src/ui/icon/logout-icon.tsx
  frontend/src/ui/mainpage/main-buttons.tsx
  frontend/src/ui/overview/sidenavbar/sidenav-button-list.tsx
  frontend/src/ui/overview/sidenavbar/sidenav.tsx
Labels: bug

#36 feat: dm & channel room/#26
  .gitignore
  frontend/package-lock.json
  frontend/package.json
  frontend/public/creator.svg
  frontend/public/operator.svg
  frontend/public/send.svg
  frontend/public/user-block.svg
  frontend/public/user-follow.svg
  frontend/public/user-kick.svg
  frontend/public/user-mute.svg
  frontend/public/user-slash.svg
  frontend/src/api/axios/axios.custom.ts
  frontend/src/api/fetch/fetch.ts
  frontend/src/api/getSearchedUser.tsx
  frontend/src/app/(overview)/(channel)/channel/[id]/layout.tsx
  frontend/src/app/(overview)/(channel)/channel/[id]/page.tsx
  frontend/src/app/(overview)/(channel)/channel/page.tsx
  frontend/src/app/(overview)/(dm)/dm/[nickname]/not-found.tsx
  frontend/src/app/(overview)/(dm)/dm/[nickname]/page.tsx
  frontend/src/app/(overview)/layout.tsx
  frontend/src/app/(overview)/profile/page.tsx
  frontend/src/app/layout.tsx
  frontend/src/app/register/page.tsx
  frontend/src/components/ChannelSocketProvider.tsx
  frontend/src/components/SocketProvider.tsx
  frontend/src/recoil/atom.ts
  frontend/src/recoil/recoilRootProvider.tsx
  frontend/src/types/interface/channel.interface.ts
  frontend/src/ui/css/globals.css
  frontend/src/ui/overview/channel/channel-list.tsx
  frontend/src/ui/overview/channel/join-channel.tsx
  frontend/src/ui/overview/channel/search-message.tsx
  frontend/src/ui/overview/sidenavbar/friend/friend-section-friend-list.tsx
  frontend/src/ui/overview/sidenavbar/friend/friend-section-mystatus.tsx
  frontend/src/ui/user-info-card.tsx
  frontend/src/utils/myState.ts
  frontend/tailwind.config.ts
  frontend/tsconfig.json
  frontend/yarn.lock
Labels: enhancement

#39 fix: 내 기본 정보 메인화면과 프로필에서 불러오기, 보안 설정 #29
  frontend/src/api/axios/axios.custom.ts
  frontend/src/api/axios/axios.instance.ts
  frontend/src/app/(overview)/profile/page.tsx
  frontend/src/app/login/page.tsx
  frontend/src/app/page.tsx
  frontend/src/app/register/page.tsx
  frontend/src/types/interface/user.interface.ts
  frontend/src/ui/overview/sidenavbar/friend/friend-section-mystatus.tsx
  frontend/src/ui/user-info-card.tsx
Labels: enhancement

#43 feat: access token protected route#42
  frontend/middleware.ts
  frontend/src/api/axios/axios.instance.ts
  frontend/src/app/layout.tsx
  frontend/src/components/ProtectedRoute.tsx
Labels: UI/UX

#57 fix: change dm socket to user socket
  frontend/src/app/(overview)/(dm)/dm/[nickname]/page.tsx
  frontend/src/components/SocketProvider.tsx
  frontend/src/recoil/atom.ts
Labels: bug

#47 feat: game room#40
  frontend/next.config.js
  frontend/public/map.svg
  frontend/src/api/axios/axios.custom.ts
  frontend/src/api/socket/game/gameKeyDown.ts
  frontend/src/api/socket/game/gameKeyUp.ts
  frontend/src/app/(overview)/(channel)/channel/page.tsx
  frontend/src/app/(overview)/(game)/game/[id]/layout.tsx
  frontend/src/app/(overview)/(game)/game/[id]/page.tsx
  frontend/src/app/(overview)/(game)/game/[id]/play/page.tsx
  frontend/src/components/ChannelSocketProvider.tsx
  frontend/src/components/GameSocketProvider.tsx
  frontend/src/components/Modals/NewGameChannelModal/NewGameChannelModal.tsx
  frontend/src/hooks/useGameChannelHandler.ts
  frontend/src/hooks/useGameEnter.ts
  frontend/src/types/interface/game.interface.ts
  frontend/src/types/type/channel-socket.type.ts
  frontend/src/types/type/game-socket.type.ts
  frontend/src/ui/button-left.tsx
  frontend/src/ui/button-right.tsx
  frontend/src/ui/overview/game/draw-game.tsx
  frontend/src/ui/overview/game/game-list.tsx
  frontend/src/ui/overview/profile/record.tsx
  frontend/yarn.lock
Labels: enhancement

#62 feat: game play를 채팅이 있는 페이지에 구현합니다. #58
  frontend/package-lock.json
  frontend/package.json
  frontend/public/symbols_cancel.svg
  frontend/src/app/(overview)/(game)/game/[id]/page.tsx
  frontend/src/app/(overview)/(game)/game/[id]/play/page.tsx
  frontend/src/app/layout.tsx
  frontend/src/app/page.tsx
  frontend/src/components/ChannelSocketProvider.tsx
  frontend/src/components/Game/GameInvite.tsx
  frontend/src/components/Game/GamePlay.tsx
  frontend/src/components/GameSocketProvider.tsx
  frontend/src/components/Modals/NewGameChannelModal/NewGameChannelModal.tsx
  frontend/src/components/SearchUser.tsx
  frontend/src/components/SocketProvider.tsx
  frontend/src/components/ToastContainerProvider.tsx
  frontend/src/recoil/atom.ts
  frontend/src/ui/css/globals.css
  frontend/src/ui/mainpage/main-buttons.tsx
  frontend/src/ui/overview/channel/message-input.tsx
  frontend/src/ui/overview/game/draw-game.tsx
  frontend/src/ui/overview/game/game-chat.tsx
  frontend/src/ui/overview/game/game-info.tsx
  frontend/src/ui/overview/game/info-header.tsx
  frontend/src/ui/overview/game/user-list.tsx
  frontend/yarn.lock
Labels: enhancement

#75 feat: add user socket to the friendlist section(status)/#74
  frontend/src/components/SocketProvider.tsx
  frontend/src/hooks/useFriendStatusListner.ts
  frontend/src/recoil/atom.ts
  frontend/src/types/type/user-socket.type.ts
  frontend/src/ui/overview/sidenavbar/friend/friend-section-friend-list.tsx
  frontend/src/ui/overview/sidenavbar/friend/friend-section.tsx
Labels: enhancement

#73 build: add qrcode to package.json
  frontend/package-lock.json
  frontend/package.json
  frontend/tsconfig.json
  frontend/yarn.lock
Labels: infra

#97 feat: game/#97
  frontend/src/api/axios/axios.custom.ts
  frontend/src/app/(overview)/(game)/game/[id]/page.tsx
  frontend/src/app/(overview)/(game)/game/page.tsx
  frontend/src/app/register/page.tsx
  frontend/src/components/Game/GamePlay.tsx
  frontend/src/components/GameSocketProvider.tsx
  frontend/src/components/Modals/Modal.tsx
  frontend/src/components/Modals/NewChatChannelModal/NewChatChannelModal.tsx
  frontend/src/components/Modals/NewGameChannelModal/NewGameChannelModal.tsx
  frontend/src/components/Modals/PrivateChannelModal/PrivateChannelModal.tsx
  frontend/src/components/Modals/PrivateGameModal/PrivateGameModal.tsx
  frontend/src/components/ProtectedRoute.tsx
  frontend/src/hooks/useCreateSingleGame.ts
  frontend/src/hooks/useGameKeyHandler.ts
  frontend/src/hooks/useMyProfileUpdator.ts
  frontend/src/hooks/useTokenValidator.ts
  frontend/src/types/enum/game.enum.ts
  frontend/src/ui/overview/game/game-list.tsx
  frontend/src/ui/overview/game/modal-game-end.tsx
Labels: bug, enhancement

#99 feat: add private channel modal
  frontend/src/components/Modals/PrivateChannelModal/PrivateChannelModal.tsx
  frontend/src/ui/overview/channel/channel-list.tsx
Labels: enhancement
